### ISSUE TITLE
The bot should reply to any DMs sent to a person in a meeting, saying they are busy

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-mscalendar#108]
Bot should auto-respond when:
- User's `activeEvents` are not empty
- and User's status is not currently set to `online`

The reason for the second condition, is because this means the user has manually set themselves to online during the meeting. The `online` status is retained until their next meeting.

There is an [open PR](https://github.com/mattermost/mattermost-plugin-mscalendar/pull/73) that will be merged soon that introduces the [`activeEvents`](https://github.com/larkox/mattermost-plugin-mscalendar/blob/7b2a6fe8e6dacdae5ae9768d59e4b138945c9dd6/server/store/user_store.go#L42) property. This property can also be added in this PR before the other PR is merged. The merge conflicts will be trivial to solve, if any.

This can be accomplish using the [`MessageHasBeenPosted`](https://developers.mattermost.com/extend/plugins/server/reference/#Hooks.MessageHasBeenPosted) hook.

**Comment by MatthewDorner** [comment]
I can take this.

**Comment by mickmister** [comment]
Awesome, thanks @MatthewDorner!

**Comment by aaronrothschild** [comment]
@MatthewDorner Looking at this PR, I'm thinking the user will want to determine if such a message is actually sent out to others:
- A setting for the user such as "Send an automatic Bot Reply when receive messages while I'm in a meeting on my O365 Calendar"
- A sub-setting with the text that the bot would respond with such as "Sorry, I'm in a meeting or scheduled event right now - reach me at bob@ben.com in an emergency" 

I worry that our generic text of something like "Sorry, Bob is in a meeting right now" is too generic.  Users may not want any automatic messages as replies.   

We should err on the side of "Not too pushy" for this feature IMO.  Thoughts @asaadmahmood

**Comment by larkox** [comment]
With the current status of the settings panel and the login flow, having this free text setting for the reply message would not be possible, but I was planning to start working on that soon.

In the meanwhile, @MatthewDorner , if you want you can add a slash command to change the reply message, and just putting the Yes/no question in the settings panel and login flow, and maybe a empty setting/step saying to change the value with the slash command.

**Comment by asaadmahmood** [comment]
@aaronrothschild Yup, I think even if we consider a feature like this, this should be optional and the user should set the message himself.

**Comment by MatthewDorner** [comment]
> In the meanwhile, @MatthewDorner , if you want you can add a slash command to change the reply message, and just putting the Yes/no question in the settings panel and login flow, and maybe a empty setting/step saying to change the value with the slash command.

I'll try to implement based on this. Could I just mention the slash command in the `TrueResponseMessage` instead of a separate step?

**Comment by larkox** [comment]
I have no preferences. Feel free to implement as you see fit. Nevertheless, whenever you have something in place, feel free to share screenshots so @asaadmahmood can take a look and give an opinion from the UX side of things.

**Comment by hanzei** [comment]
@mickmister I did remove this from our board given that it's a community contribution.

**Comment by jfrerich** [comment]
PR Merged. Closing!
