### ISSUE TITLE
Idea: Bot Responds to user who is in a meeting

### ISSUE THREAD

**Issue by aaronrothschild** [mattermost/mattermost-plugin-mscalendar#119]
When a user is messaged, while in a meeting - optionally, a bot could respond to the user who sent a message saying they are in a meeting at the moment and to expect a delayed response.

**Comment by mickmister** [comment]
@aaronrothschild Already have a ticket here :) https://github.com/mattermost/mattermost-plugin-mscalendar/issues/108 . Do you mind helping with the wording of the auto response? And I suppose this would be a configurable setting?

@asaadmahmood This was requested by a customer. What are your thoughts?
