### ISSUE TITLE
Replace the `0` with `12` to indicate noon and midnight

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-mscalendar#127]
The current settings panel uses `0` to indicate midnight or noon. 
This confusing especially since we have AM and PM as people never refer to noon as 0 hours.
We should make this a `12`.

![0-Hour](https://user-images.githubusercontent.com/35588783/81638962-9897c380-93e8-11ea-8736-e137a00ee438.PNG)

**Comment by larkox** [comment]
If I remember correctly, I did it so 0 is midnight, and 12 is noon (if you change from 0:45AM to 0:45PM it will be updated to 12:45PM).
Is this not working? Or would you prefer to see the 12 as another option when selecting AM times?
