### ISSUE TITLE
Daily Summary is not displaying at set time

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-mscalendar#130]
On a recent build from master I'm seeing that the daily summary is not show to the test user at the preset time. The job is running when expected but the summary is not shown. 

Debug logging for the corresponding time shows `(log ERROR) Error during daily summary job. err=msgraph ViewCalendar batch request: 400 Bad Request: {"error":{"code":"BadRequest","message":"Id property cannot be empty."}}`

Steps:
- Login as the test user
- Set summary time 
- Wait for summary
**Observed**: Summary is nor shown and logging shows an error

**Comment by mickmister** [comment]
@DHaussermann I want to make sure I understand the behavior

- Daily summary job runs
- User that is supposed to receive their summary does not receive it ever
- An error occurs during that processing time
- Is there another connected user that has the same set time?
