### ISSUE TITLE
On mobile app - /mscalendar settings does not redirect user to the bot DM channel

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-mscalendar#159]
On the RN app, if a user types `/mscalendar settings` the user is not redirected to the bot DM channel where the settings panel is shown.
This makes the app seem unresponsive as nothing else is displayed in the channel after posting the message.
(webapp is not affected by this issue)

Steps:
- Login from RN
- Open a channel that is not the MS Calendar bot DM
- Type `mscalendar setting`
**Expected**: User is re-directed to the Bot DM where they can see the panel
**Observed**: User stays in current channel

**Comment by larkox** [comment]
Known bug. Has to be solved on the Mobile client or worked around on the plugin.

**Comment by larkox** [comment]
This was discussed on [this conversation](https://community.mattermost.com/core/pl/1q5njkttdtr758jf6h7jt9guxe) (added here for context during triage)
