### ISSUE TITLE
Enabling mscalendar plugin Requires Admin Consent

### ISSUE THREAD

**Issue by ahmaddanialmohd** [mattermost/mattermost-plugin-mscalendar#179]
The following error is displayed when enabling the plugin without admin consent despite it being optional in the documentation [here](https://mattermost.gitbook.io/plugin-mscalendar/installation/installing-the-plugin):

> Optional: Set users who should have administrative privileges with this plugin

```
{"error":"msgraph GetMailboxSettings: 403 Forbidden: {\"error\":{\"code\":\"ErrorAccessDenied\",\"message\":\"Access is denied. Check credentials and try again.\"}}","details":"Unauthorized."}
```

Once the permissions were enabled,  the calendar plugin works.

**Comment by larkox** [comment]
The line "Click Grant admin consent for... to grant the permissions for the application. You're all set for configuration inside of Azure." in the Readme should cover this case.
