### ISSUE TITLE
Allow development mode when checking license

### ISSUE THREAD

**Issue by hanzei** [mattermost/mattermost-plugin-mscalendar#194]
Instead of allowing the plugin to run if an E20 license is enabled, it should also run if development mode is enabled.

The new check should make use https://github.com/mattermost/mattermost-plugin-api/pull/72 and be similar to https://github.com/mattermost/mattermost-plugin-incident-response/blob/c17fa2029a3f855b2a0f41510e4b3485a05744c5/server/plugin.go#L57-L59.

**Comment by cjmartian** [comment]
I'll take this one
