### ISSUE TITLE
Add command autocomplete for nested subcommands

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-mscalendar#224]
Currently some nested subcommands are not shown in the command autocomplete. For instance:

`/mscalendar summary` is shown but `/mscaeldnar summary view` is not shown

**Comment by raghavaggarwal2308** [comment]
This issue is currently not present in the master branch. Closing as completed
![image](https://github.com/user-attachments/assets/de8ff7a9-e160-4ca8-90e4-ad23f7736a90)
