### ISSUE TITLE
Remove `Calendar.ReadWrite` permission in favor of `Calendar.Read` permission

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-mscalendar#238]
Since the feature set of this plugin is focused on reading calendar event information, and no functionality is meant to modify calendar events, we should "downgrade" the permission to be read-only.

**Comment by ThiefMaster** [comment]
I guess ReadWrite is only for accepting calendar invites? Is there a less wide permission that still allows accepting?

In any case I (and my organization's mail admin) would also prefer not having to grant write access...

**Comment by mickmister** [comment]
@ThiefMaster Thanks for pointing this out. I'll close this, as it is indeed required for using the plugin due to the calendar event invitation responses.

**Comment by ThiefMaster** [comment]
Would you consider making the invitation response feature configurable (and thus not require that permission if one doesn't need this functionality (or accept a Pull Request if someone else implemented this)?

**Comment by mickmister** [comment]
@ThiefMaster I'm curious what would happen if this permission was just left disabled on Microsoft's side. Sure we would accept a pull request, as it seems it would provide value in your real situation.

**Comment by ThiefMaster** [comment]
I'd expect buttons in Mattermost that fail when you click them ;)
