### ISSUE TITLE
Implement user `disconnect` slash command

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-mscalendar#24]
#### Summary

The user should be able to disconnect their Mattermost account from their Microsoft account at any time. Using a `/mscalendar disconnect` command, any user data in the plugin's kv store should be cleaned up.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-21991

**Comment by hanzei** [comment]
@mickmister Should this be a HW?

**Comment by mickmister** [comment]
@hanzei Yes I had meant to set up the titles/labels as such. Thanks for catching this!
