### ISSUE TITLE
Status sync job exits if an error happens for a single user

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-mscalendar#244]
Hi, we are having an issue with the mscalender plugin `v1.1.0`. Everything was working fine and then they stopped getting notifications for meetings and status updates. We checked the logs and they were getting the error `"error":"invalid_grant","error_description":"AADSTS700082: The refresh token has expired due to inactivity`. They just generated a new token and installed it, and that resolved the issue with meeting notifications, however status updates are not working (it's not updating their status to indicate they are in a meeting). The error they are getting now in the logs is `Error during user status sync job. err=not found` They have tried restarting the plugin, reconnecting the plugin to their O365 account, and also reconnecting their account.  Any thoughts on what check next?

_Issue created from a [Mattermost message](https://community.mattermost.com/_redirect/pl/gtyhjtzgmtdb7efqa9cwuzub9w) *by @ewwollesen*._

**Comment by mickmister** [comment]
We should also try to be more descriptive with the error messages from the jobs such as the status sync job. The `not found` error we're currently getting here is not very helpful, though I assume it's coming from here:

https://github.com/mattermost/mattermost-plugin-mscalendar/blob/548fd466dd2f00c83df42086ef709f4b4f90a9fc/server/mscalendar/availability.go#L66

**Comment by Kshitij-Katiyar** [comment]
@mickmister By this ``` we would want to limit how many we log```. Here the limit is some kind of number like 100 logs or it means we should restrict (try to reduce) the logs we print.
