### ISSUE TITLE
Mattermost/Office 365 - Calendar Notifications

### ISSUE THREAD

**Issue by jess72x** [mattermost/mattermost-plugin-mscalendar#262]
My team is looking into using Mattermost, and we are trying to gain some information on how how Mattermost integrate with other apps that we currently use. I read that you can accept or decline calendar event invites from Mattermost. 

Does Mattermost send you notification reminders before your event? In MS Outlook you get a pop up notification typically 15 minutes prior to your meeting and you have the option to 'snooze' the reminder. It will then pop up again after the snooze time. Does Mattermost have this function as well?

**Comment by mickmister** [comment]
Hi @jess72x, thanks for filing this issue

> Does Mattermost send you notification reminders before your event? In MS Outlook you get a pop up notification typically 15 minutes prior to your meeting

Yes, the user will receive a message in Mattermost 10 minutes before an upcoming meeting. Individual users can disable this feature for themselves as well.

> and you have the option to 'snooze' the reminder. It will then pop up again after the snooze time. Does Mattermost have this function as well?

This plugin does not have this the snooze functionality.

I've created an issue https://github.com/mattermost/mattermost-plugin-mscalendar/issues/263 for us to explain more about the functionality of the plugin in the README. Thanks again for creating this issue :+1:

**Comment by mickmister** [comment]
Closing as this discussion seems resolved
