### ISSUE TITLE
Buttons are unreadable in dark themes

### ISSUE THREAD

**Issue by Rulqu** [mattermost/mattermost-plugin-mscalendar#333]
The button coloring is unreadable in dark themes like Indigo or Onyx. Example in picture.
![image](https://github.com/mattermost/mattermost-plugin-mscalendar/assets/11457361/272cc87d-4912-4218-b8c5-e4565d8ecfa3)

**Comment by fmartingr** [comment]
Hey @Rulqu, this is an issue with the Mattermost styles, rather than the plugin itself.

There's an open PR to address the issue here: https://github.com/mattermost/mattermost/pull/24116 Please follow that for updates.

Closing since there's nothing we can do and this has to be fixed server side.
