### ISSUE TITLE
error "Received invalid response from the server" when trying to install the plugin

### ISSUE THREAD

**Issue by KuestenKeks** [mattermost/mattermost-plugin-mscalendar#365]
Hey there, when I try to upload the latest release .tar.gz in the Mattemorst system console, the error "Received invalid response from the server." appears a few seconds after I clicked the upload button. Any idea what could be wrong? Kind regards!

**Comment by mickmister** [comment]
Hi @KuestenKeks, thanks for filing this issue. It's possible this is related to the maximum file upload size on your server. Can you please check this and make sure it agrees with the size of the `tar.gz` file being uploaded?
