### ISSUE TITLE
Account connection does not work

### ISSUE THREAD

**Issue by KuestenKeks** [mattermost/mattermost-plugin-mscalendar#367]
This is the sequence of steps, when I try to connect the plugin to my M365 account:

1. I click on the bot message: 
![grafik](https://github.com/mattermost/mattermost-plugin-mscalendar/assets/1938271/182697f3-c38f-4043-913a-637a972cc607)

2. A window pops up where I can choose my M365 account. It says I'm already logged in ("Angemeldet"), probably because I've also installed and configured the [Teams meeting plugin](https://github.com/mattermost-community/mattermost-plugin-msteams-meetings): 
![grafik](https://github.com/mattermost/mattermost-plugin-mscalendar/assets/1938271/df46b835-58ca-433d-a759-90cb5e9167ec)

3. This message box is shown where it says that certain permissions are required, that need to be approved by an administrator. When I click on "Genehmigungsanforderung", administrators get an approval request: 
![grafik](https://github.com/mattermost/mattermost-plugin-mscalendar/assets/1938271/2e580daa-0936-44c4-8469-8c977263d17e)

4. I approve the permission request in the azure portal

5. I try again to connect the plugin to my M365 account, but I still get the same message box as in step 3, where I can create a new approval request despite that the previous one has already been approved.

That's how it played out yesterday. I thought maybe waiting a day would change something, but it's just the same today.
I've configured the plugin as described [in the documentation](https://github.com/mattermost/mattermost-plugin-mscalendar/blob/master/docs/admin-guide.md#configuration). The configuration was very similar to the MS Teams plugin, which works just fine. When connecting the Teams plugin with my M365 account, There was no permission approval needed, I did not get a message like I did here in step 3.

Kind regards!

**Comment by jprusch** [comment]
Same here. After switching back to 1.2.1 it's working again.

**Comment by Kshitij-Katiyar** [comment]
@KuestenKeks @jprusch Can you please tell me the mattermost server version and other details you can give me about the environment and error maybe.

**Comment by jprusch** [comment]
Desktop logs are clean.

This is whats displayed:
![image](https://github.com/mattermost/mattermost-plugin-mscalendar/assets/9337414/3c7f3140-3f24-458b-be7e-6638d9b631d3)

Mattermost server log (only lines which contain "calen")

[mscal-log-9.8.1-1.3.0.log](https://github.com/mattermost/mattermost-plugin-mscalendar/files/15471555/mscal-log-9.8.1-1.3.0.log)

In contrast to the 1.2.1 plugin the connect message is shown opening the M$ connect dialog. With 1.2.1 this doesn't open, it's just connected.

**Comment by jprusch** [comment]
Yes, I discussed with devs & we decided that it doesn't make sense to have a non-working release in the marketplace. I'll test the next release before it's heading to the marketplace.
