### ISSUE TITLE
Show additional commands to admin when running `/mscalendar` or `/mscalendar help`

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-mscalendar#39]
#### Summary

Similar to the functionality implemented in https://github.com/mattermost/mattermost-plugin-jira/pull/402, we should show admin-only commands separate from the regular end-user commands in the output of `/mscalendar` and `/mscalendar help`. At the moment, these include `connect_bot` and `disconnect_bot`.

**Comment by larkox** [comment]
Since there are no longer admin-only commands, we are closing this issue.
