### ISSUE TITLE
The help text for viewcal slash command does not matches the response

### ISSUE THREAD

**Issue by AayushChaudhary0001** [mattermost/mattermost-plugin-mscalendar#392]
While testing the plugin, I found that the help text for viewcal slash command does not match with the response of the slash command. The helper text shows that the slash command will show the events for the upcoming week, whereas, the response shows all the events for the ongoing week without considering the current day.

**Steps to reproduce:-**
1. Connect the Microsoft account with the Mattermost account.
2. Run the "/mscalendar viewcal" slash command.

The helper text shows that the command will show the events in the upcoming week, whereas the response shows all the events in the ongoing week(for previous days as well).

**Lets take an example here:-** 
I ran the viewcal slash command here on Tuesday, but the response consisted of the events which were already planned and completed on Monday(a day before). Also, as the helper text shows the upcoming week, the current week should not be considered.

![image](https://github.com/user-attachments/assets/2bc56c48-8995-4719-a76a-8d5ceaa6cff8)

![image](https://github.com/user-attachments/assets/3e4f93d9-f17c-443a-8e26-70ba078fbbd4)

**Suggestion:-** If we change the word "upcoming" to "ongoing/current", then every case will be handled and the situation would be solved.

**Comment by raghavaggarwal2308** [comment]
@wiggin77 Can someone help us in understanding about what exactly is the expected behaviour of this command?

**Comment by wiggin77** [comment]
@esethna would you prefer the wording changed or the behaviour?  See above.

**Comment by esethna** [comment]
@wiggin77 @raghavaggarwal2308 I'd propose we change the help text to `View your events for the week.`

If it's easy to remove the tables for days in the past that would be a good win, but not necessary if it adds too much complexity.

**Comment by Kshitij-Katiyar** [comment]
@wiggin77 @esethna @AayushChaudhary0001 

The following function retrieves events when the /viewcal command is triggered. This command fetches all events scheduled between `current time - 24 hours` and `current time + 14 * 24 hours`.
```
events, err := c.Engine.ViewCalendar(c.user(), time.Now().Add(-24*time.Hour), time.Now().Add(14*24*time.Hour))
```

![Screenshot from 2024-08-14 10-46-46](https://github.com/user-attachments/assets/046a54f7-3e2d-4d29-9cce-7913b4d41b79)
![Screenshot from 2024-08-14 10-48-48](https://github.com/user-attachments/assets/9e069acd-f8e3-4d2d-89dd-c89b79e68a48)
P.S: The screenshots were taken at 10:45 AM on August 14, 2024.

Please advise on how we should proceed. My suggestions are:
- Updating the time frame for retrieving events to `From: current time` `To: current time + 7 days`
- Updating the time frame for retrieving events to `From: Monday of the current week` `To: Sunday of the current week`
- Updating only the help text and keep the current functionality

We will need to update the help text regardless of the chosen approach.

**Comment by Kshitij-Katiyar** [comment]
@wiggin77 @esethna  @AayushChaudhary0001  

The following function retrieves events when the /viewcal command is triggered. This command fetches all events scheduled between `current time - 24 hours` and `current time + 14 * 24 hours`.
```
events, err := c.Engine.ViewCalendar(c.user(), time.Now().Add(-24*time.Hour), time.Now().Add(14*24*time.Hour))
```

![Screenshot from 2024-08-14 10-46-46](https://github.com/user-attachments/assets/046a54f7-3e2d-4d29-9cce-7913b4d41b79)
![Screenshot from 2024-08-14 10-48-48](https://github.com/user-attachments/assets/9e069acd-f8e3-4d2d-89dd-c89b79e68a48)
P.S: The screenshots were taken at 10:45 AM on August 14, 2024.

In the current fix, we have changed the time duration for the viewcal command to `From: Current day` `To: Current day + 14 * 24hours`

**Comment by wiggin77** [comment]
> The following function retrieves events when the /viewcal command is triggered.

@Kshitij-Katiyar the screen-shot doesn't give a complete picture of the behaviour since not all days have calendar events.  Assuming every day has a calendar event, what events are displayed when the command is run Wednesday the 14th?  Will it include Wed, Thurs, Fri and then every day the next week?

**Comment by raghavaggarwal2308** [comment]
@wiggin77 The above screenshot is showing that it will display the events of today and 14 days after that (Including all the days in between). 

Current logic:
The following function retrieves events when the /viewcal command is triggered. This command fetches all events scheduled between current time - 24 hours and current time + 14 * 24 hours.
Ex: If we run the command on 14th  at 1:00 PM, it with display all the events from 13th (1:00 PM) to 29th (1:00 PM).

Update logic in https://github.com/mattermost/mattermost-plugin-mscalendar/pull/399:
We have changed the time duration for the viewcal command to From: Current day To: Current day + 14 * 24hours
Ex:  If we run the command on 14th  at 1:00 PM, it with display all the events from 14th (12:00 AM) to 29th (1:00 PM).
