### ISSUE TITLE
Add missing commands to help text

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-mscalendar#45]
#### Summary

The help text should be updated to include all existing commands. The help text and command autocomplete message needs to be updated whenever a new command is added. The autocomplete is updated in https://github.com/mattermost/mattermost-plugin-mscalendar/pull/38 .

Also, the help text should be implemented in the currently unused `getHelp()` function, which can then be referenced in `c.help`.

**Comment by DHaussermann** [comment]
@aaronrothschild this is this something we can address for the beta? 
The help text also contains references to features that where not implemented.

**Comment by aaronrothschild** [comment]
@DHaussermann Yes, let's address those before release then.  

@mickmister Can I make the changes to the help text in the code directly? (without doing all the stuff you mentioned above) :
- Remove any non-public commands that didn't make it to release
- Update the autocomplete text pane to reflect those changes
