### ISSUE TITLE
Improve the disconnect message to return something when the user is already disconnected

### ISSUE THREAD

**Issue by larkox** [mattermost/mattermost-plugin-mscalendar#49]
When the user is disconnected, if you type /mscalendar disconnect the command just says that could not execute, but it gives no ephemeral explaining why.

It should return a message like "You are already disconnected from MSCalendar"

**Comment by hanzei** [comment]
@larkox Could this be a HW?

**Comment by larkox** [comment]
From my perspective, for sure 👍

**Comment by mickmister** [comment]
As an aside for handling command errors, if we return a user-facing string *and* an error, the string is ignored. I think we should instead use the string if provided, even when we have an error.

https://github.com/mattermost/mattermost-plugin-mscalendar/blob/864a161240b2cb28b3496c1dcc45a16204f23e54/server/command/command.go#L89-L92

Instead, use the `out` return value even if there is an error:
```go
if err != nil { 
	return out, errors.WithMessagef(...)
} 
```
