### ISSUE TITLE
Accept/Decline a meeting invite in a chat window

### ISSUE THREAD

**Issue by larkox** [mattermost/mattermost-plugin-mscalendar#53]
Whenever you receive an invite, the bot should send you a message with the meeting, and allow you to accept or decline the meeting from the message.

**Comment by larkox** [comment]
@levb @mickmister After further inspection on the code, this is already done.

Right now it is using a Select in order to decide what to do with the event. On our previous talk, we talked about using buttons instead of the select, but here may be working nice.

The only improvement I would make on the code here is that once you have answered, the post is updated so you can no longer update the status, it will only state: "You have accepted this meeting". What do you think?

Also, keep in mind that this "You have accepted this meeting" would not be updated if the user updates the status in the calendar.

**Comment by levb** [comment]
@larkox all i can say is, "let's get it to maximum accordance with the spec". I initially implemented it with buttons, but then switched to a select to be able to reflect the current acceptance status.
