### ISSUE TITLE
Create README.md file

### ISSUE THREAD

**Issue by jfrerich** [mattermost/mattermost-plugin-mscalendar#6]
- [x] Install Directions
- [ ] Available Slash Commands

**Comment by MatthewDorner** [comment]
Link to [www.portal.azure.com](www.portal.azure.com) here doesn't work: https://github.com/mattermost/mattermost-plugin-mscalendar/blame/864a161240b2cb28b3496c1dcc45a16204f23e54/README.md#L22

**Comment by mickmister** [comment]
Closing in favor of https://github.com/mattermost/mattermost-plugin-mscalendar/issues/51
