### ISSUE TITLE
Add Google Calendar support

### ISSUE THREAD

**Issue by levb** [mattermost/mattermost-plugin-mscalendar#7]
This plugin has been designed with the idea that we can add different remote backends. It appears likely at this point that we want to repurpose it to become the "Mattermost Calendar" plugin.

The `./server/remote` types may need a lot of adjustments to be conceptually compatible with different backends, but in theory we should be able to add a Google-specific implementation.

Would  also need to abstract OAuth2 since it's materially different, and add the configuration settings to allow the choice of the backend.

**Comment by levb** [comment]
cc @hahmadia - saw your hackathon submission, was wondering if you'd consider helping to consolidate into a single "Calendar" plugin that supports multiple backends.

**Comment by hahmadia** [comment]
> cc @hahmadia - saw your hackathon submission, was wondering if you'd consider helping to consolidate into a single "Calendar" plugin that supports multiple backends.

Sure! We can have a meeting and talk more about this as I'm not sure how to do that. Hope we can discuss further after hackathon in a meeting of some sort.

**Comment by mickmister** [comment]
@levb I think we should close this as we are on track to creating two calendar plugins now
