### ISSUE TITLE
Delete OAuth state from KV store after OAuth process is complete

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-mscalendar#71]
#### Summary

Currently the OAuth state data is left persisting in the KV store after the when it should be removed when the authentication process is finished.

**Comment by avddvd** [comment]
@mickmister I would like to work on this issue. 

I thought of couple of ways to manage OAuth2 state

1. Use `StoreTTL(key string, data []byte, ttlSeconds int64)` instead of `Store(key string, data []byte)` with an appropriate time to live value.

2. Call `Delete(key string)` right after state is verified with `VerifyOAuth2State`

@mickmister I would think approach 1 is cleaner once an appropriate time to live value is agreed on.

Please suggest

**Comment by mickmister** [comment]
Hi @avddvd, thanks for picking up this issue!

Using option one would ensure it gets removed regardless of what happens after storing, so that sounds good to me. The OAuth process is virtually instantaneous, barring user intervention time. I think 5 minutes is an appropriate, generous time window.

**Comment by mickmister** [comment]
@avddvd To add this, I suggest responding with a user-friendly message when they missed the time window. Something like "Your authentication token has expired. Please try and reconnect."

**Comment by avddvd** [comment]
@mickmister When user misses the time window (i.e: takes more than 5 minutes to finish OAuth), the following happens 
- managed OAuth state gets deleted
- as a result, `VerifyOAuth2State` returns an error specifically `AppError`

As far as my understanding of OAuth flow, the above scenario forces user to reconnect (restart OAuth)

Would you suggest to return `errors.New("Your authentication token has expired. Please try and reconnect.")` message from `VerifyOAuth2State` ?

**Comment by mickmister** [comment]
> Would you suggest to return `errors.New("Your authentication token has expired. Please try and reconnect.")` message from `VerifyOAuth2State`?

Yeah that sounds good to me :+1:

**Comment by mickmister** [comment]
@avddvd ^

**Comment by avddvd** [comment]
Hey @mickmister 

This check is already in place
`	if string(data) != state {
		return errors.New("authentication attempt expired, please try again")
	}`
